import json
import sys
import subprocess
import os
from datetime import datetime
from github import Github

def generate_markdown_table(stats_list, org_name, start_date, end_date):
    """
    Generate a markdown table from issue statistics.
    
    Args:
        stats_list (list): List of statistics dictionaries from GitHubIssuesAnalyzer
        org_name (str): Name of the GitHub organization
        start_date (str): Start date of the report period
        end_date (str): End date of the report period
        
    Returns:
        str: Markdown formatted table
    """
    markdown = "---\n"
    markdown += "title: Archival Candidates Report\n"
    markdown += "labels: archival, automated\n"
    markdown += "---\n\n"
    markdown += f"# {org_name} Repository Archival Candidates Report\n\n"
    markdown += "This report was automatically generated by the [archival-identifier](https://github.com/DSACMS/archival-identifier) tool to identify potential archival candidates based on:"
    markdown += "\n- Development activity\n- Reuse via forks\n- [OpenSSF Criticality Score](https://github.com/ossf/criticality_score)\n- Repository Contents\n\n"
    markdown += "For more information about the criteria used to determine archival candidacy, please refer to the [archival-identifier documentation](https://github.com/DSACMS/archival-identifier).\n\n"
    markdown += f"## Results: {start_date} to {end_date}\n\n"
    markdown += "| Repository | Open Issues | Closed Issues | Open PRs | Merged PRs | Closed PRs | Releases | Commits | Criticality Score | Forks | Active Forks | Is Empty/README-Only | Status |\n"
    markdown += "|---|---|---|---|---|---|---|---|---|---|---|---|---|\n"
    
    for repo, stats in stats_list.items():
        markdown += f"| {repo} | {stats['issues_open_count']} | {stats['issues_closed_count']} | {stats['pr_open_count']} | {stats['pr_merged_count']} | {stats['pr_closed_count']} | {stats['release_count']} | {stats['commit_count']} | {stats['criticality_score']} | {stats['forks_count']} | {stats['active_forks_count']} | {stats['is_empty_or_readme_only']} | {stats['status']} |\n"
    
    return markdown

def write_markdown_file(markdown_content, output_path="archival_candidates_report.md"):
    """
    Write markdown content to a file.
    
    Args:
        markdown_content (str): The markdown content to write
        output_path (str): Path where the markdown file should be saved
    """
    with open(output_path, 'w') as f:
        f.write(markdown_content)
    print(f"Markdown report written to {output_path}")

def calculate_months_in_range(start_date, end_date):
    """
    Calculate the number of calendar months covered by a date range.

    Args:
        start_date (str): Start date in YYYY-MM-DD format
        end_date (str): End date in YYYY-MM-DD format

    Returns:
        int: Number of months in range (inclusive of start and end months)
    """
    start = datetime.strptime(start_date, "%Y-%m-%d")
    end = datetime.strptime(end_date, "%Y-%m-%d")

    if end < start:
        raise ValueError("END_DATE must be on or after START_DATE")

    return (end.year - start.year) * 12 + (end.month - start.month) + 1

def define_status_determination(stats, months_in_range=1):
    """
    Determine the status of a repository based on its statistics.
    
    stats (dict): A dictionary containing development activity statistics for a repository
        
    str: The determined status of the repository (e.g., "Active", "Dormant", "Archived")
    """
    criticality_score_threshold = float(os.getenv("CRITICALITY_SCORE_THRESHOLD", 2.5))

    # Logic for status determination
    if stats.get("archived", True):
        return "Archived"
    
    # Repository has no content (empty or README-only), classify as Dormant
    if stats.get("is_empty_or_readme_only") in ["Empty", "README-only"]:
        return "Dormant"
    
    # Repository shipped releases, classify as Active
    if stats.get("release_count", 0) > 0:
        return "Active"
    
    # Repository shipped >2 user/non-bot commits per month, classify as Active
    commits_threshold = months_in_range
    print("COMMIT_COUNT: ", stats.get("commit_count", 0))
    print("MONTHS_IN_RANGE: ", months_in_range)
    if stats.get("commit_count", 0) > commits_threshold:
        return "Active"

    # Repository is low criticality and has low activity across key metrics, classify as Dormant
    activity_fields = [
        "issues_open_count",
        "issues_closed_count",
        "pr_open_count",
        "pr_merged_count",
        "pr_closed_count",
    ]
    # Check if all activity fields are below 3, indicating low activity
    issue_pr_check = all(stats.get(field, 0) < 3 for field in activity_fields)

    # Count how many activity fields have a value of 0, indicating no activity in those areas
    zero_value_count = sum(1 for field in activity_fields if stats.get(field, 0) == 0)
    zero_count_check = zero_value_count >= 3

    if stats.get("criticality_score", 0) <= criticality_score_threshold and (issue_pr_check or zero_count_check):
        return "Dormant"
    
    return "Active"

def analyze_fork_activity(repo, start_date, end_date):
    """
    Analyze the activity of forks for a given repository.
    
    repo (str): name of repository
    start_date (str): start date for the reporting period (YYYY-MM-DD)
    end_date (str): end date for the analysis period (YYYY-MM-DD)
    
    dict: A dictionary containing statistics about the forks (e.g., number of forks, recent activity)
    """

    g = Github(os.getenv("GITHUB_AUTH_TOKEN"))
    org_name = os.getenv("ORG_NAME")
    
    start_date = datetime.strptime(start_date, "%Y-%m-%d")
    end_date = datetime.strptime(end_date, "%Y-%m-%d")

    repo_obj = g.get_repo(f"{org_name}/{repo}")
    forks = list(repo_obj.get_forks())
    forks_count = len(forks)
    print( f"{repo} has {forks_count} forks.")
    active_forks = []

    for fork in forks:
        print(f"Analyzing fork: {fork.full_name}...")
        
        # Check if fork is ahead by unique commits within reporting period
        try:
            
            # Retrieves commits from the reporting period
            fork_commits = fork.get_commits(since=start_date, until=end_date)
            fork_commit_shas = { commit.sha for commit in fork_commits }
            parent_commits = repo_obj.get_commits(since=start_date, until=end_date) # TODO: Use commits data from data.json
            parent_commit_shas = { commit.sha for commit in parent_commits }

            # Uses the set difference to determine if there are unique commits in the fork that are not in the parent repository
            unique_fork_commits = fork_commit_shas.difference(parent_commit_shas)
            is_ahead = len(unique_fork_commits) > 0

            if is_ahead:
                active_forks.append(fork)
                print(f"Fork {fork.full_name} is ahead of parent: {is_ahead} with {len(unique_fork_commits)} unique commits in the reporting period.")

        except Exception as e:
            # Fork has an empty default branch or encountered other issues. Classify as inactive.
            if e.status == 404:
                print("Error")
            else:
                print(f"\nCould not compare {fork.full_name}: {e}")
        
    print(f"{len(active_forks)} active forks found for {repo}.")
    return forks_count, len(active_forks)


def main():
    # Setting variables from environment and command line arguments
    org_name = os.getenv("ORG_NAME")
    start_date = os.getenv("START_DATE")
    end_date = os.getenv("END_DATE") or datetime.now().strftime("%Y-%m-%d")
    months_in_range = calculate_months_in_range(start_date, end_date)
    
    development_activity_file = sys.argv[1]
    criticality_score_file = sys.argv[2]
    empty_repo_report_file = sys.argv[3]

    with open(development_activity_file, 'r') as f:
        repository_development_data = json.load(f)
    
    with open(criticality_score_file, 'r') as f:
        criticality_score_data = json.load(f)

    with open(empty_repo_report_file, 'r') as f:
        empty_repo_data = json.load(f)
    print (empty_repo_data)

    stats= {}

    for repo in repository_development_data["repos"]:
        print(f"Analyzing {repo['name']}: Development Activity")

        # Calculate statistics for the repository
        stats[repo["name"]] = {
            "archived": repo["archived"],
            "issues_open_count": len([issue for issue in repo["issues"] if issue["state"] == "open"  and issue["author"] != "dependabot[bot]" and issue["author"] != "github-actions[bot]"]),
            "issues_closed_count": len([issue for issue in repo["issues"] if issue["state"] == "closed"]),
            "pr_open_count": len([pr for pr in repo["pulls"] if pr["state"] == "open" and pr["author"] != "dependabot[bot]" and pr["author"] != "github-actions[bot]"]),
            "pr_merged_count": len([pr for pr in repo["pulls"] if pr["state"] == "closed" and pr["merged"] == True]),
            "pr_closed_count": len([pr for pr in repo["pulls"] if pr["state"] == "closed" and pr["merged"] == False]),
            "release_count": len(repo["releases"]),
            "commit_count": len([commit for commit in repo["commits"] if commit["author"] != "dependabot[bot]" and commit["author"] != "github-actions[bot]"])
        }

        # Run OpenSSF Criticality Score
        print(f"Analyzing {repo['name']}: Criticality Score")
        criticality_score = criticality_score_data.get(repo["name"], 0)
        stats[repo["name"]]["criticality_score"] = criticality_score

        # Analyze fork activity
        print(f"Analyzing {repo['name']}: Usage via Forks")
        forks_count, active_forks_count = analyze_fork_activity(repo["name"], start_date, end_date)
        stats[repo["name"]]["forks_count"] = forks_count
        stats[repo["name"]]["active_forks_count"] = active_forks_count

        ## Assess repository contents (e.g. is it empty or README-only?)
        print(f"Analyzing {repo['name']}: Repository Contents")
        repo_full_name = f"{org_name}/{repo['name']}"
        if repo_full_name in empty_repo_data.get("readmeOnly", []):
            stats[repo["name"]]["is_empty_or_readme_only"] = "README-only"
        elif repo_full_name in empty_repo_data.get("empty", []):
            stats[repo["name"]]["is_empty_or_readme_only"] = "Empty"
        else:
            stats[repo["name"]]["is_empty_or_readme_only"] = "Has Content"

        # Determine the status of the repository
        stats[repo["name"]]["status"] = define_status_determination(stats[repo["name"]], months_in_range)

    # Generate and write markdown file
    markdown_content = generate_markdown_table(stats, org_name, start_date, end_date)
    write_markdown_file(markdown_content)

if __name__ == "__main__":
    main()
